baseURL = "http://localhost:1313/"
languageCode = "fr-fr"
title = "PypTech Chronicles"
theme = "toha"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  homeHeader = "Bienvenue sur PypTech Chronicles"
  homeSubheader = "Linux, Réseau, DevOps et Vie d'un Tech en Reconversion"
  homeContent = "Découvrez mes articles sur les sujets techniques et mon parcours de reconversion."

  [[params.sections]]
    title = "Linux"
    description = "Explorez les fondamentaux et avancées de Linux dans des articles détaillés."
    url = "/categories/linux/"

  [[params.sections]]
    title = "Réseau"
    description = "Découvrez les réseaux informatiques, VLANs, et optimisation d'infrastructures."
    url = "/categories/reseau/"

  [[params.sections]]
    title = "DevOps"
    description = "Plongez dans l'univers DevOps, avec Docker, Kubernetes, et l'automatisation."
    url = "/categories/devops/"

  [[params.sections]]
    title = "Vie d'un Tech en Reconversion"
    description = "Suivez mon parcours de reconversion dans l'IT et mes réflexions personnelles."
    url = "/categories/reconversion/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/:year/:month/:slug/"